"""empty message

Revision ID: 8571a6058161
Revises: 
Create Date: 2026-06-20 19:42:29.882668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8571a6058161'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_expiry'), ['expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_user_id'), ['user_id'], unique=False)

    op.create_table('runners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('years_running', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('is_mentor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strava_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strava_token_user_id'), ['user_id'], unique=True)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_runner_id', sa.Integer(), nullable=False),
    sa.Column('target_runner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_runner_id'], ['runners.id'], ),
    sa.ForeignKeyConstraint(['target_runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streak_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['streak_by_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streak')
    op.drop_table('favorites')
    with op.batch_alter_table('strava_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strava_token_user_id'))

    op.drop_table('strava_token')
    op.drop_table('runners')
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_expiry'))

    op.drop_table('password_reset')
    op.drop_table('user')
    op.drop_table('messages')
    # ### end Alembic commands ###
